plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
}

version = "1.21.4"
group = "tisiry"

repositories {
    maven { url = "https://fabricmc.net" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.4"

    mappings "net.fabricmc:yarn:1.21.4+build.2:v2"

    modImplementation "net.fabricmc:fabric-loader:0.16.9"

    modImplementation "net.fabricmc.fabric-api:fabric-api:0.113.0+1.21.4"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}
