plugins {
    id 'fabric-loom' version '1.16-SNAPSHOT'
}

version = "1.21.8"
group = "tisiry"

repositories {
    maven { url = "https://fabricmc.net" }
    mavenCentral()
}

dependencies {
    // Версия Minecraft
    minecraft "com.mojang:minecraft:1.21.8"

    // Обновленные маппинги Yarn для 1.21.8
    mappings "net.fabricmc:yarn:1.21.8+build.1:v2"

    // Рекомендуемая версия Loader
    modImplementation "net.fabricmc:fabric-loader:0.16.14"

    modImplementation "net.fabricmc.fabric-api:fabric-api:0.136.1+1.21.8"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}
